### ISSUE TITLE
Problem with multiple ip's on one host

### ISSUE THREAD

**Issue by baryshev** [rekby/lets-proxy#18]
Certificate request fails with error like ``Can't local lookup ip for domain 'www.x.x.x.192': lookup www.x.x.x.192 on x.x.x.x:53: no such host`` when DNS pointed to ip address which is not the default interface for that host.

**Comment by rekby** [comment]
It haven't problem with multiple ip addresses on host.

I double check about ip addresses on different interfaces - it work ok.

I think the problem is add IP address after start lets-proxy and handle traffic right after add IP.
Lets proxy renew list of allowed ip addresses once per hour default. It is ok for manual add IP.

I think about work with dynamic add/remove ip addresses.

Now i see 2 workaround:
1. Add all of possible ips in key --allowed-ips
2. Restart lets-proxy after add new ip. It will close all opened connections, but force to renew list of allowed IP addresses.

**Comment by rekby** [comment]
Try version v0.13.0.0 https://github.com/rekby/lets-proxy/releases/tag/v0.13.0.0

If your servers can handle many dynamic ip addresses set --allow-ips-refresh=0. If you have only one switched ips it will work fine without additional  keys.
