### ISSUE TITLE
Proxy http 01 validation Nginx Wiki

### ISSUE THREAD

**Issue by skojin** [rekby/lets-proxy#54]
I think wiki page need to be updated in Nginx section.

Pass only /.well-known/acme-challenge to Nginx same as for Apache
```
  location ~ /\.well-known/acme-challenge {
      proxy_pass       http://127.0.0.1:4443;
      proxy_set_header Host      $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
```

**Comment by rekby** [comment]
Hello.
Nginx example is good idea!

Try version:
```
  location ^~ /.well-known/acme-challenge/ {
      proxy_pass       http://127.0.0.1:4443;
      proxy_set_header Host      $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
```
It will work some faster and doesn't proxy traffix for /.well-known/acme-challenge-something-else/
https://nginx.ru/en/docs/http/ngx_http_core_module.html#location
If the longest matching prefix location has the “^~” modifier then regular expressions are not checked.

**Comment by brsergey** [comment]
this works too

**Comment by skojin** [comment]
this works too

**Comment by flyoffthehandle** [comment]
I'm trying to finally knock this out with nginx. i've only ever been able to get one backend to work (i'm going for a reverse proxy that forwards all of the traffic for a subdomains.domain.com and SSL through lets encrypt. I've added the location block for .well-known to my default and my cloud.conf vhosts. I can't tell if you are also instructing to change or remove nginx listening on 80/443 because as you can imagine lets-proxy seems to run fine but immediately errors about the port 443 being used. I know it needs 443 eventually but 80 is what LE will need for all the cert grabbing right?

**Comment by rekby** [comment]
Port 80 have to be listened by nginx and port 433 must be free (let's proxy will listen port 433).

**Comment by flyoffthehandle** [comment]
Thank you for getting back to me so fast.
